package com.arbhlabs.taprelay.band

// Generated by TapRelay_Band9/tools/make-icons.mjs from tools/icon-catalogue.mjs - do not edit.
// One row per band icon: key, category, keywords ("|"-separated, "!" = weak). PNGs: assets/band_icons/<key>.png.
internal object BandIconData {
    const val ROWS: String = """
lightbulb	light	!lamp|!light|!licht|!leuchte|!lampe|!bulb
emoji_objects	light	corner|ecke|floor lamp|stehlampe|standing lamp|reading|lese
light	light	ceiling|decke|deckenlampe|pendant|hauptlicht|main light|overhead
wb_incandescent	light	edison|filament|vintage|retro bulb
fluorescent	light	strip|led strip|lightstrip|light strip|tube|neon|stripe|streifen|leiste
highlight	light	spot|spotlight|downlight|strahler|track light
wb_iridescent	light	wall|wand|sconce|panel|nanoleaf|hexa
tungsten	light	warm|cozy|cosy|gemütlich|gemuetlich
nightlight	light	night|nacht|bedside|nightstand|nachttisch|nachtlicht
settings_brightness	light	tv lamp|tv light|backlight|ambilight|bias light|monitor light|screen light|gradient
light_mode	light	daylight|tageslicht|sunlight|bright
wb_twilight	light	sunrise|sunset|wake light|dawn|dusk|sonnenaufgang
wb_sunny	light	outdoor|garden light|porch|aussen|außen
lens_blur	light	ambient|glow|mood light|stimmungslicht
blur_on	light	fairy|string lights|lichterkette|christmas|weihnacht|twinkly
flashlight_on	light	flashlight|torch|taschenlampe
flashlight_off	light	flashlight off|torch off
local_fire_department	light	candle|kerze|flame|flamme
fireplace	light	fireplace|kamin
brightness_high	light	brightness|helligkeit|full bright
brightness_low	light	dim|dimmen|gedimmt
bright_plus	light	brighter|heller|brightness up
bright_minus	light	darker|dunkler|brightness down
palette	light	color|colour|farbe|rgb
brightness_auto	light	auto dim|auto-dim|autodim|auto brightness
desk	room	desk|schreibtisch|workstation|setup
table_restaurant	room	table|tisch|dining|esstisch|esszimmer
bed	room	bed|bett|bedroom|schlafzimmer
king_bed	room	master bedroom|guest bed|gästebett
weekend	room	sofa|couch|living|wohnzimmer|lounge
chair	room	chair|stuhl|armchair|sessel
kitchen	room	kitchen|küche|kueche|fridge|kühlschrank
countertops	room	counter|worktop|arbeitsplatte|island
bathtub	room	bathroom|bath|bad|badezimmer|tub|wanne
shower	room	shower|dusche
wc	room	toilet|wc|klo|restroom
stairs	room	stairs|treppe|hallway|hall|flur|corridor|gang
garage	room	garage|carport
yard	room	garden|garten|yard|backyard
balcony	room	balcony|balkon
deck	room	terrace|terrasse|patio|deck|pergola
pool	room	pool|schwimmbad
hot_tub	room	jacuzzi|whirlpool|sauna|hot tub
roofing	room	attic|dachboden|loft|roof
house	room	house|home|haus|zuhause|all|alle|everything|alles|whole
cottage	room	cabin|hütte|cottage|shed|schuppen
meeting_room	room	office|büro|buero|study|arbeitszimmer
child_care	room	nursery|kids|kinder|baby|children
checkroom	room	closet|wardrobe|schrank|kleiderschrank|dressing
theaters	room	cinema|kino|home theater|heimkino|media room
sports_bar	room	bar|beer|bier|man cave
door_front	security	door|tür|tuer|entrance|eingang|front door|haustür
door_sliding	security	sliding door|schiebetür|patio door
window	security	window|fenster
blinds	security	blind|blinds|jalousie|rollo|shutter|rollladen|rolladen|shade
curtains	security	curtain|vorhang|gardine|drapes
lock	security	lock|schloss|abschließen|lock pc|lock screen
lock_open	security	unlock|aufschließen|open lock
key	security	key|schlüssel|keybox
shield	security	security|sicherheit|alarm system|arm|guard
videocam	security	camera|kamera|cam|webcam|cctv|ring
doorbell	security	doorbell|klingel|türklingel
sensors	security	sensor|motion|bewegung|presence|präsenz
notifications	security	bell|notification|benachrichtigung|chime|gong
alarm	security	alarm|wecker|wake up|aufstehen
timer	security	timer|stopwatch|stoppuhr
garage_door	security	!gate|tor|einfahrt
air	climate	air purifier|purifier|luftreiniger|air|luft|breeze
ac_unit	climate	ac|aircon|air con|air conditioner|klima|klimaanlage|cooling|kühlen|cool
mode_fan_off	climate	fan|ventilator|lüfter|luefter|tower fan|ceiling fan
fan_plus	climate	fan up|fan faster|fan high|stärker
fan_minus	climate	fan down|fan slower|fan low|schwächer
hvac	climate	vent|vents|hood|extractor|dunstabzug|abzug|ventilation|lüftung|exhaust
thermostat	climate	thermostat|heating|heizung|heater|radiator|heizkörper|heat|temperature|temperatur
temp_plus	climate	warmer|wärmer|temp up|temperature up
temp_minus	climate	colder|kälter|temp down|temperature down
heat_pump	climate	heat pump|wärmepumpe
water_drop	climate	humidifier|luftbefeuchter|humidity|feuchtigkeit|diffuser
dry	climate	dehumidifier|entfeuchter|dryer|trockner
severe_cold	climate	freezer|gefrier|frost
whatshot	climate	boiler|hot water|warmwasser|therme
outlet	power	socket|steckdose|outlet
power	power	plug|stecker|smart plug|zwischenstecker
power_settings_new	power	power button|an aus|shutdown|herunterfahren|power off
toggle_on	power	toggle|switch|schalter|!relay
electric_bolt	power	energy|strom|electricity|power meter|verbrauch
bolt	power	bolt|quick|boost|turbo
solar_power	power	solar|pv|photovoltaik|balkonkraftwerk
battery_charging_full	power	charger|charging|laden|ladegerät|battery|akku
ev_station	power	wallbox|ev charger|car charger|ladestation|tesla
local_laundry_service	appliance	washer|washing|waschmaschine|laundry|wäsche
iron	appliance	iron|bügeleisen|steamer
microwave	appliance	microwave|mikrowelle|oven|ofen|backofen
blender	appliance	blender|mixer|smoothie
coffee_maker	appliance	coffee machine|coffee maker|kaffeemaschine|espresso|siebträger|nespresso
soup_kitchen	appliance	kettle|wasserkocher|cooker|kocher|slow cooker|rice cooker
outdoor_grill	appliance	grill|bbq|barbecue
cleaning_services	appliance	vacuum|staubsauger|roomba|robot|saugroboter|clean|putzen|mop
router	appliance	router|wifi|wlan|internet|modem|fritz
print	appliance	printer|drucker|3d print
aquarium	appliance	aquarium|fish|fisch|tank
pets	appliance	pet|dog|cat|hund|katze|feeder|futter
water	appliance	pump|pumpe|sprinkler|irrigation|bewässerung|fountain|brunnen
local_florist	appliance	plant|pflanze|flower|blume|grow|watering|gießen
grass	appliance	lawn|rasen|mower|mähroboter|mow
park	appliance	tree|baum|christmas tree|tannenbaum
tv	screen	tv|fernseher|television|telly
connected_tv	screen	apple tv|chromecast|fire tv|firetv|shield tv|roku|streaming
smart_display	screen	youtube|netflix|video|twitch|prime video|disney
cast	screen	cast|mirror|spiegeln|airplay
monitor	screen	monitor|screen|display|bildschirm
desktop_access_disabled	screen	display off|screen off|monitor off|bildschirm aus
computer	screen	pc|computer|rechner|tower|gaming pc
laptop	screen	laptop|notebook|macbook
desktop_windows	screen	windows|desktop|win+d
sports_esports	screen	xbox|playstation|ps5|ps4|console|konsole|gaming|game|controller|steam
videogame_asset	screen	nintendo|rumble|controller rumble
keyboard	screen	keyboard|tastatur|shortcut|hotkey|keys|tastenkürzel
mouse	screen	mouse|maus|click|klick
screen_share	screen	screen share|stream|obs|broadcast|go live
open_in_new	screen	open|launch|öffnen|starten
language	screen	website|web|url|browser|chrome|link
restart_alt	screen	restart|reboot|neustart
nights_stay	screen	pc sleep|hibernate|standby|ruhezustand
photo_camera	screen	screenshot|photo|foto|picture
movie	screen	movie|film|movie night|filmabend
projector	screen	!beamer|projector
play_pause	media	play/pause|play pause|play / pause|playpause
play_arrow	media	play|abspielen|resume|start music
pause	media	pause
stop	media	stop|stopp
skip_next	media	next|skip|nächster|naechster|weiter
skip_previous	media	previous|prev|zurück|vorheriger|back track
fast_forward	media	fast forward|forward|vorspulen
fast_rewind	media	rewind|zurückspulen
fullscreen	media	fullscreen|vollbild|full screen
close_fullscreen	media	exit fullscreen|escape|esc
subtitles	media	captions|subtitles|untertitel|cc
crop_16_9	media	theater mode|theatre|kinomodus|wide
slow_motion_video	media	slower|langsamer|slow down
speed	media	faster|schneller|speed|playback speed
switch_video	media	next video|nächstes video
picture_in_picture_alt	media	mini player|miniplayer|picture in picture|pip
flip_to_front	screen	alt tab|alt+tab|switch app|app wechseln
view_quilt	screen	task view|win+tab|windows overview
toggle_off	power	turn off|ausschalten
forward_5	media	forward 5|5s forward|skip 5|+5s|vor 5
replay_5	media	back 5|5s back|rewind 5|-5s|zurück 5
forward_10	media	forward 10|10s forward|skip 10|+10s|vor 10
replay_10	media	back 10|10s back|rewind 10|-10s|zurück 10
forward_30	media	forward 30|30s forward|skip intro|+30s
replay_30	media	back 30|30s back|-30s
vol_plus	media	volume up|vol up|louder|lauter|vol+|volume+
vol_minus	media	volume down|vol down|quieter|leiser|vol-|volume-
volume_off	media	mute|stumm|silence sound|unmute
volume_up	media	volume|lautstärke|sound|ton|audio
music_note	media	music|musik|song|spotify|apple music|tidal
queue_music	media	playlist|queue|warteschlange
shuffle	media	shuffle|zufall
repeat	media	repeat mode|loop|wiederholen modus
speaker	media	speaker|lautsprecher|sonos|echo|homepod|boombox|soundbar
speaker_group	media	multiroom|speaker group|party mode
headphones	media	headphones|kopfhörer|headset|airpods|earbuds|buds
podcasts	media	podcast|audiobook|hörbuch
radio	media	radio|fm
mic	media	mic|mikrofon|microphone|voice
mic_off	media	mute mic|mic mute|mic off|discord mute|push to talk
headset_mic	media	voice chat|discord|teamspeak|call|meeting audio
videocam_off	media	camera off|webcam off|cam off|video off
fiber_manual_record	media	record|aufnahme|rec|clip
graphic_eq	media	equalizer|eq|signature|signatures|haptic signature
smartphone	phone	phone|handy|smartphone|pixel|find my phone
do_not_disturb_on	phone	dnd|do not disturb|nicht stören|focus mode
notifications_off	phone	silent|lautlos|quiet|ruhig
vibration	phone	vibrate|vibration|haptic|haptics|vibrieren
call	phone	call|anrufen|dial
sms	phone	sms|message|nachricht|text|whatsapp|telegram
wifi	phone	!wifi toggle|hotspot
bluetooth	phone	bluetooth
airplanemode_active	phone	airplane|flugmodus|flight mode
screen_rotation	phone	rotate|rotation|drehen
battery_saver	phone	battery saver|stromsparen|power saving
location_on	phone	location|gps|standort|places
directions_car	phone	car|auto|drive|fahren|commute
map	phone	map|karte|navigate|navigation
settings_remote	phone	remote|fernbedienung|remote mode
visibility	phone	aod|always on|always-on
schedule	phone	clock|uhr|time|zeit|aod clock
contrast	phone	monochrome|contrast|kontrast|grayscale|graustufen
task_alt	phone	confirm|bestätigen|done|erledigt|check
replay	phone	repeat last|again|nochmal|replay|last
history	phone	history|verlauf|log history
tune	phone	settings|einstellungen|tune|config
webhook	phone	webhook|http|api|ifttt|zapier|n8n|home assistant|hass
auto_awesome	phone	scene|szene|preset|magic
auto_fix_high	phone	routine|automation|magic action|sequence|ablauf
event	phone	calendar|kalender|meeting|termin
work	phone	work|arbeit|job|work mode
school	phone	school|schule|uni|study mode|lernen
shopping_cart	phone	shopping|einkaufen|groceries|einkauf
attach_money	phone	money|geld|pay|bezahlen|budget
celebration	phone	party|feier|celebrate
nightlife	phone	club|disco|dance|tanzen
medication	health	!dose|pill|pills|tablet|tablette|medication|medikament|meds|capsule|kapsel|vitamin
medication_liquid	health	syrup|sirup|drops|tropfen|liquid|tincture|tinktur
vaccines	health	injection|shot|vaccine|spritze|insulin|pen
healing	health	bandage|pain|schmerz|ibuprofen|paracetamol|aspirin|painkiller
psychology	health	mood|stimmung|anxiety|angst|adhd|brain|focus|ritalin|adderall|elvanse
sick	health	sick|krank|nausea|übelkeit|headache|kopfschmerz
monitor_heart	health	heart rate|pulse|puls|hr|ecg|ekg|bpm
favorite	health	heart|love|herz|aod log hr
monitor_weight	health	weight|gewicht|scale|waage
bloodtype	health	blood|blut|blood pressure|blutdruck|glucose|zucker
bedtime	health	sleep|schlafen|good night|gute nacht|bedtime|melatonin|nap
dark_mode	health	dark|dunkel|moon|mond|night mode
self_improvement	health	meditate|meditation|yoga|relax|breathe|atmen
fitness_center	health	workout|gym|training|sport|lift|pushups
directions_run	health	run|laufen|jog|joggen|cardio
directions_walk	health	walk|spaziergang|gehen|steps|schritte
spa	health	spa|massage|wellness|skin|skincare|cream|creme
local_drink	health	water intake|drink water|glass|wasser trinken|hydrate
water_bottle	health	!water|wasser
local_cafe	health	coffee|kaffee|caffeine|koffein|latte|cappuccino|cup
emoji_food_beverage	health	tea|tee|matcha|chai
wine_bar	health	wine|wein|prosecco|champagne|sekt
local_bar	health	cocktail|alcohol|alkohol|shot glass|vodka|whisky|gin|rum|liquor
liquor	health	bottle|flasche|spirits
smoking_rooms	health	smoke|rauchen|cigarette|zigarette|kippe|joint|bowl|weed|cannabis|thc|cbd|blunt|pipe|bong|spliff|kiffen|hash|dab
vaping_rooms	health	vape|vaping|dampfen|e-cig|ecig|juul|elf bar|pod
smoke_free	health	quit|no smoke|rauchfrei|nicotine free|craving
energy_drink	health	!energy|red bull|monster|pre-workout|preworkout
restaurant	health	meal|food|essen|lunch|dinner|mittag|abendessen|breakfast|frühstück|snack
rice_bowl	health	rice|reis|cereal|müsli|muesli|oatmeal|porridge|soup bowl
local_pizza	health	pizza
bakery_dining	health	bread|brot|croissant|toast|bakery
icecream	health	ice cream|eis|dessert|sweets|süßes|candy
cake	health	cake|kuchen|birthday|geburtstag
egg	health	egg|ei|eggs|protein
nutrition	health	salad|salat|veggies|gemüse|vegan|fiber
science	health	supplement|creatine|kreatin|nootropic|lab|test
star	generic	star|stern|favourite|favorite item
diamond	generic	diamond|premium|special
extension	generic	extension|plugin|addon|puzzle
category	generic	misc|other|sonstiges
interests	generic	hobby|interests
rocket_launch	generic	launch sequence|rocket|go
flag	generic	flag|marker|goal|ziel
push_pin	generic	pin|pinned|anheften
bookmark	generic	bookmark|lesezeichen|saved
label	generic	label|tag|nfc
filter_1	generic	
filter_2	generic	
filter_3	generic	
filter_4	generic	
filter_5	generic	
filter_6	generic	
filter_7	generic	
filter_8	generic	
filter_9	generic	
"""
}
